# Generated by Django 4.2 on 2023-06-02 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_url', models.CharField(max_length=10, unique=True, verbose_name='短链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_enabled', models.IntegerField(choices=[(0, '未启用'), (1, '启用')], default=1, verbose_name='启用状态')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '短链接',
                'verbose_name_plural': '短链接',
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_url', models.URLField(verbose_name='原始链接')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_enabled', models.IntegerField(choices=[(0, '未启用'), (1, '启用')], default=1, verbose_name='启用状态')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.link', verbose_name='短链接')),
            ],
            options={
                'verbose_name': '原始链接',
                'verbose_name_plural': '原始链接',
                'unique_together': {('original_url', 'link')},
            },
        ),
    ]
